name: offline_banner
description: "A customizable Flutter widget that shows an animated banner when offline and an online popup when internet is restored, with retry support and configurable position."
version: 1.0.4
homepage: https://github.com/VenuNeosoft/Internet_connectivity_pluggin.git
repository: https://github.com/VenuNeosoft/Internet_connectivity_pluggin.git
issue_tracker: https://github.com/VenuNeosoft/Internet_connectivity_pluggin/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

  plugin:
    platforms:
      android:
        package: com.example.offline_banner  # â† Update this with your desired package name
        pluginClass: OfflineBannerPlugin
      ios:
        pluginClass: OfflineBannerPlugin


  assets:
    - assets/demo.gif
platforms:
  android:
  ios:

  